/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AlerteSchema extends BaseModel {
  static $columns = ['createdAt', 'declencheeLe', 'estResolue', 'groupeSanguin', 'hopitalId', 'id', 'message', 'resolueLe', 'type', 'updatedAt'] as const
  $columns = AlerteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare declencheeLe: DateTime | null
  @column()
  declare estResolue: boolean | null
  @column()
  declare groupeSanguin: string | null
  @column()
  declare hopitalId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare message: string
  @column.dateTime()
  declare resolueLe: DateTime | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BadgeSchema extends BaseModel {
  static $columns = ['createdAt', 'debloqueLe', 'donneurId', 'id', 'niveau', 'updatedAt'] as const
  $columns = BadgeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare debloqueLe: DateTime | null
  @column()
  declare donneurId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare niveau: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BonsDemandeSchema extends BaseModel {
  static $columns = ['createdAt', 'groupeSanguinPatient', 'hopitalId', 'id', 'medecinId', 'nomPatient', 'quantiteNecessaire', 'statut', 'updatedAt'] as const
  $columns = BonsDemandeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare groupeSanguinPatient: string
  @column()
  declare hopitalId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare medecinId: string
  @column()
  declare nomPatient: string
  @column()
  declare quantiteNecessaire: number | null
  @column()
  declare statut: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DemandesAcceSchema extends BaseModel {
  static $columns = ['createdAt', 'emailDemandeur', 'hopitalId', 'id', 'message', 'nomDemandeur', 'roleDemande', 'statut', 'updatedAt'] as const
  $columns = DemandesAcceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare emailDemandeur: string
  @column()
  declare hopitalId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare message: string | null
  @column()
  declare nomDemandeur: string
  @column()
  declare roleDemande: string
  @column()
  declare statut: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DonneurSchema extends BaseModel {
  static $columns = ['codeDonneur', 'createdAt', 'dateDernierDon', 'dateEligibiliteSuivante', 'donneesQrCode', 'groupeSanguin', 'id', 'niveauBadge', 'totalDons', 'updatedAt', 'utilisateurId'] as const
  $columns = DonneurSchema.$columns
  @column()
  declare codeDonneur: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dateDernierDon: DateTime | null
  @column.date()
  declare dateEligibiliteSuivante: DateTime | null
  @column()
  declare donneesQrCode: string | null
  @column()
  declare groupeSanguin: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare niveauBadge: string | null
  @column()
  declare totalDons: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare utilisateurId: string | null
}

export class DonSchema extends BaseModel {
  static $columns = ['agentId', 'createdAt', 'dateDon', 'donneurId', 'hopitalId', 'id', 'questionnaireReponses', 'statut', 'typePoche', 'updatedAt', 'volume'] as const
  $columns = DonSchema.$columns
  @column()
  declare agentId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare dateDon: DateTime
  @column()
  declare donneurId: string
  @column()
  declare hopitalId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare questionnaireReponses: any | null
  @column()
  declare statut: string
  @column()
  declare typePoche: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare volume: number | null
}

export class HopitauxSchema extends BaseModel {
  static $columns = ['adresse', 'commune', 'createdAt', 'departement', 'email', 'estActif', 'id', 'latitude', 'longitude', 'nom', 'telephone', 'type', 'updatedAt'] as const
  $columns = HopitauxSchema.$columns
  @column()
  declare adresse: string | null
  @column()
  declare commune: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare departement: string | null
  @column()
  declare email: string | null
  @column()
  declare estActif: boolean | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare latitude: number | null
  @column()
  declare longitude: number | null
  @column()
  declare nom: string
  @column()
  declare telephone: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LogSchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'description', 'entity', 'id', 'userId'] as const
  $columns = LogSchema.$columns
  @column()
  declare action: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare entity: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: number | null
}

export class MembresHopitalSchema extends BaseModel {
  static $columns = ['createdAt', 'hopitalId', 'id', 'updatedAt', 'utilisateurId'] as const
  $columns = MembresHopitalSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare hopitalId: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare utilisateurId: string
}

export class NotificationSchema extends BaseModel {
  static $columns = ['createdAt', 'envoyeeLe', 'estLue', 'id', 'message', 'titre', 'type', 'updatedAt', 'utilisateurId'] as const
  $columns = NotificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare envoyeeLe: DateTime | null
  @column()
  declare estLue: boolean | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare message: string
  @column()
  declare titre: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare utilisateurId: string
}

export class PochesSangSchema extends BaseModel {
  static $columns = ['createdAt', 'dateExpiration', 'donId', 'groupeSanguin', 'id', 'statut', 'typePoche', 'updatedAt', 'volume'] as const
  $columns = PochesSangSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare dateExpiration: DateTime
  @column()
  declare donId: string
  @column()
  declare groupeSanguin: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare statut: string
  @column()
  declare typePoche: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare volume: number | null
}

export class RegistrePslSchema extends BaseModel {
  static $columns = ['bonDemandeId', 'createdAt', 'id', 'motif', 'retourLe', 'traceLe', 'transfereVers', 'updatedAt'] as const
  $columns = RegistrePslSchema.$columns
  @column()
  declare bonDemandeId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare motif: string | null
  @column.dateTime()
  declare retourLe: DateTime | null
  @column.dateTime()
  declare traceLe: DateTime | null
  @column()
  declare transfereVers: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RendezVousSchema extends BaseModel {
  static $columns = ['createdAt', 'dateRdv', 'donneurId', 'hopitalId', 'id', 'membreId', 'note', 'statut', 'updatedAt'] as const
  $columns = RendezVousSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare dateRdv: DateTime
  @column()
  declare donneurId: string
  @column()
  declare hopitalId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare membreId: string | null
  @column()
  declare note: string | null
  @column()
  declare statut: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ResultatsTestSchema extends BaseModel {
  static $columns = ['createdAt', 'donId', 'groupeSanguinConfirme', 'hepatiteB', 'hepatiteC', 'id', 'testeLe', 'testePar', 'tpha', 'updatedAt', 'vdl', 'vih'] as const
  $columns = ResultatsTestSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare donId: string
  @column()
  declare groupeSanguinConfirme: string | null
  @column()
  declare hepatiteB: boolean | null
  @column()
  declare hepatiteC: boolean | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare testeLe: DateTime | null
  @column()
  declare testePar: string | null
  @column()
  declare tpha: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vdl: boolean | null
  @column()
  declare vih: boolean | null
}

export class StocksSanguinSchema extends BaseModel {
  static $columns = ['createdAt', 'groupeSanguin', 'hopitalId', 'id', 'misAJourLe', 'quantite', 'seuilCritique', 'seuilFaible', 'updatedAt'] as const
  $columns = StocksSanguinSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare groupeSanguin: string
  @column()
  declare hopitalId: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare misAJourLe: DateTime | null
  @column()
  declare quantite: number | null
  @column()
  declare seuilCritique: number | null
  @column()
  declare seuilFaible: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['commune', 'createdAt', 'dateNaissance', 'departement', 'email', 'estActif', 'id', 'motDePasse', 'nom', 'nomComplet', 'photoProfil', 'prenom', 'role', 'telephone', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare commune: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dateNaissance: DateTime | null
  @column()
  declare departement: string | null
  @column()
  declare email: string
  @column()
  declare estActif: boolean | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare motDePasse: string
  @column()
  declare nom: string | null
  @column()
  declare nomComplet: string | null
  @column()
  declare photoProfil: string | null
  @column()
  declare prenom: string | null
  @column()
  declare role: string | null
  @column()
  declare telephone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
